apiVersion: v1
kind: Namespace
metadata:
  name: elasticsearch

---

apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: elasticsearch
  namespace: elasticsearch
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: elasticsearch
    spec:
      containers:
      - name: elasticsearch
        image: ryutah/elasticsearch
        env:
        - name: discovery.type
          value: single-node
        ports:
        - containerPort: 9200
        - containerPort: 9300
        imagePullPolicy: IfNotPresent

---

apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: kibana
  namespace: elasticsearch
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: kibana
    spec:
      containers:
      - name: kibana
        image: ryutah/kibana
        ports:
        - containerPort: 5601
        env:
        - name: ELASTICSEARCH_URL
          value: http://elasticsearch
        imagePullPolicy: IfNotPresent

---

kind: Service
apiVersion: v1
metadata:
  name: elasticsearch
  namespace: elasticsearch
spec:
  type: LoadBalancer
  selector:
    app: elasticsearch
  ports:
  - name: core
    port: 9200
    targetPort: 9200

---

kind: Service
apiVersion: v1
metadata:
  name: kibana
  namespace: elasticsearch
spec:
  type: LoadBalancer
  selector:
    app: kibana
  ports:
  - name: http
    port: 80
    targetPort: 5601
